WebUI/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class Department
    {
        public int Id { get; set; }
        [Required]
        [MinLength(length: 6, ErrorMessage = "Lütfen 6 karakterden uzun değer giriniz.")]
        [MaxLength(length: 255, ErrorMessage = "Lütfen daha kısa bir metin giriniz.")]
        public string Name { get; set; }
        [MinLength(length: 2, ErrorMessage = "Lütfen 2 karakterden uzun değer giriniz.")]
        [MaxLength(length: 500, ErrorMessage = "Lütfen daha kısa bir metin giriniz.")]
        public string Description { get; set; }
    }
}

WebUI/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Attributes;
using WebUI.Database;
using WebUI.Models;
using WebUI.Models.ViewModels;

namespace WebUI.Controllers
{
    [Authentication]
    public class DepartmentController : Controller
    {
        public TelephoneDirectoryDbContext DbContext { get; }
        public DepartmentController()
        {
            this.DbContext = new TelephoneDirectoryDbContext();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new DepartmentAddViewModel());
        }

        [HttpPost]
        public ActionResult Add(DepartmentAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = model.Department;
                DbContext.Department.Add(entity);
                DbContext.SaveChanges();
                return RedirectToAction("List", "Employee");
            }
            else
                ModelState.AddModelError("PostError", "Departman Ekleme İşlemi Hatalı.");

            return View(model);
        }



    }
}

WebUI/Views/Department/Add.cshtml
@model WebUI.Models.ViewModels.DepartmentAddViewModel
@{
    ViewBag.Title = "Add";
}

<h2>Departman Ekle</h2>
@using (Html.BeginForm("Add", "Department", FormMethod.Post))
{
    <div class="col-md-9">
        <div class="form-group">
            <label for="exampleFormControlInput1">Departman Adı</label>
            @Html.TextBoxFor(m => Model.Department.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => Model.Department.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Departman Açıklaması</label>
            @Html.TextBoxFor(m => Model.Department.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => Model.Department.Description, "", new { @class = "text-danger" })
        </div>
        @Html.ValidationMessage("PostError", new { @class = "post-error" })
        <button type="submit" class="btn btn-lg btn-pill btn-success">Ekle</button>
    </div>
}

WebUI/Views/Department/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

WebUI/Views/Department/List.cshtml
@model WebUI.Models.ViewModels.DepartmentListViewModel
@{
    ViewBag.Title = "List";
}

<h2>List</h2>
<div class="left-panel col-xs-4">
    @foreach (var item in Model.Departments)
    {
        <a href="@Url.Action("List","Department")" data-id="@item.Id" class="list-item">
            <span>@item.Name </span>
            @if (item.Description != null)
            {
                <span>@item.Description</span>
            }
        </a>
    }
</div>